### ISSUE TITLE
Feature: Use new JetStream Client API

### ISSUE THREAD

**Issue by g41797** [memphisdev/memphis.go#118]
[New JetStream Client API](https://nats.io/blog/preview-release-new-jetstream-client-api/)  was developed 2 months ago
Current version [1.28.0](https://pkg.go.dev/github.com/nats-io/nats.go/jetstream)
Consider usage of new api in Memphis Go SDK
see [Migration to new JetStream API](https://natsbyexample.com/examples/jetstream/api-migration/go)

**Comment by idanasulinmemphis** [comment]
It is on the roadmap and will happen very soon. Target version: 1.3.0
