### ISSUE TITLE
version that matches the server

### ISSUE THREAD

**Issue by gedw99** [memphisdev/memphis.go#29]
is it possible to indicate in the README what version of the CLI matches what version of the Server ?

**Comment by yanivbh1** [comment]
Hey @gedw99 ,
The CLI is compatible with the latest version of the cluster. btw, have you upgraded to 0.3.6?
Great point about the version compatibility  and will be inserted to the README

**Comment by gedw99** [comment]
> 0.3.6?

not yet...
