### ISSUE TITLE
Unify connect.go channels into one

### ISSUE THREAD

**Issue by OrMemphis** [memphisdev/memphis.go#3]
many listeners that does the same work more or less can be unified into one listener.

**Comment by Vrashabh-Sontakke** [comment]
Please add a little bit of discription for that issue.

**Comment by OrMemphis** [comment]
I think we'll put this issue on hold since many changes to the interface of Memphis <-> SDKs is going to change.
also, we depend on [this issue](https://github.com/memphisdev/memphis.go/issues/4) for any progress on this one.
