### ISSUE TITLE
Reconnection flow test

### ISSUE THREAD

**Issue by OrMemphis** [memphisdev/memphis.go#6]
the Conn object holds two connections, one to NATS and the other to Memphis, 
The NATS reconnection logic is already implemented by NATS, however the connection with Memphis is TCP based and the SDK supposed to manage the reconnection logic.

We need to test the latter.
Example scenario:
bring up Memphis, connect with the SDK with reconnection interval of X with 3 reconnections, take Memphis down for X < interval < 2X => SDK should reconnect successfully

**Comment by idanasulinmemphis** [comment]
Released in the latest version
