### ISSUE TITLE
Consumer timeout error

### ISSUE THREAD

**Issue by krzwiatrzyk** [memphisdev/memphis.go#95]
As in the title, I receive an error each **pullInterval** time:
![image](https://github.com/memphisdev/memphis.go/assets/52850037/1a65080f-8e53-40ce-a751-8d939fa79f60)

My code:
```

func FunFactConsumer(ctx context.Context) {
    conn, err := memphis.Connect(config.Memphis().Host, config.Memphis().Username, memphis.Password(config.Memphis().Password), memphis.Timeout(time.Second * 30))
    if err != nil {
        zap.S().Fatal(err)
    }
    defer conn.Close()

    consumer, err := conn.CreateConsumer("fun-facts", "gfun", memphis.PullInterval(15*time.Second))

    if err != nil {
        zap.S().Fatal(err)
    }

    handler := func(msgs []*memphis.Msg, err error, ctx context.Context) {
        if err != nil {
            zap.S().Error(err)
            return
        }

        for _, msg := range msgs {
			zap.S().Info("Memphis message: " + string(msg.Data()))
            msg.Ack()
			zap.S().Infof("Memphis headers: %+v", msg.GetHeaders())
        }
    }

	ctx = context.WithValue(ctx, "key", "value")
	consumer.SetContext(ctx)
    consumer.Consume(handler)

    <-ctx.Done()

	zap.S().Info("Stopping Memphis consumer")
	consumer.StopConsume()
}

```

**Comment by krzwiatrzyk** [comment]
FYI:
- I have tested if setting `mempthis.Timeout` to value higher than `memphis.PullInterval` will help, but without success
- I have created consumer based on default example in Memphis

**Comment by idanasulinmemphis** [comment]
Hi @krzwiatrzyk, thanks for bringing it to our attention.
This happens when no new messages are available to be consumed, I agree that it is a bad experience so I pushed a fix which will be released in our coming version
https://github.com/memphisdev/memphis.go/commit/8c07c3773433240894319e15ab2f5ee527ba36cd
